spring:
  application:
    name: discipline
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.iogap.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:discipline}
      auto-index-creation: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  security:
    user:
      name: ${APP_USERNAME:admin}
      password: ${APP_PASSWORD:admin}

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG
    com.buseni.discipline: DEBUG
    org.springframework.data.mongodb: DEBUG 