spring:
  application:
    name: discipliner
  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.iogap.mongodb.net/${DB_NAME}?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework.security: DEBUG
    com.buseni.discipline: DEBUG
    org.springframework.data.mongodb: DEBUG

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080} 